[package]
name = "aw-core"
version = "0.1.0"
edition = "2024"

[dependencies]
arm-decoder = { path = "../arm-decoder" }
binaryen = { path = "../../../binaryen-rs" }
binaryen-module = { path = "../module" }
capstone = "0.14.0"
clap = { version = "4.6.1", features = ["cargo", "derive"] }
disarm64 = "0.1.26"
elf = "0.8.0"
rayon = "1.12.0"
